/*
 * Copyright (C) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class AudioEncoder{
  public static aacLc:string = "aacLc";
  public static aacEld:string = "aacEld";
  public static aacHe:string = "aacHe";
  public static amrNb:string = "amrNb";
  public static amrWb:string = "amrWb";
  public static flac:string = "flac";
  public static pcm16bits:string = "pcm16bits";
  public static opus:string = "opus";
  public static wav:string = "wav";
}